import { useEffect, useMemo, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { CatalogueItem, PricingWorkspace } from './TreatmentPricing'
import { supabase } from './lib/supabase'

type Patient = { id: string }
type Plan = { id: string; additional_adjustment: number | null }
type Item = { id: string; treatment_catalogue_id: string | null; treatment_name_snapshot: string; tooth_or_region: string | null; quantity: number; unit_price_snapshot: number; discount_percent: number; discount_amount: number; final_price: number; status: string; custom_price: boolean; price_adjustment_reason: string | null }
const statuses = ['Planned', 'Accepted', 'In Progress', 'Completed', 'Deferred', 'Cancelled']
const money = (value: number) => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
const calc = (price: number, quantity: number, discount: number) => { const subtotal = Math.max(0, price) * Math.max(1, quantity); const discountAmount = Math.min(subtotal, subtotal * Math.max(0, Math.min(100, discount)) / 100); return { subtotal, discountAmount, final: subtotal - discountAmount } }

export function TreatmentPlan({ patient, workspace, onNotice }: { patient: Patient; workspace: PricingWorkspace; onNotice: (message: string) => void }) {
  const [catalogue, setCatalogue] = useState<CatalogueItem[]>([]), [plan, setPlan] = useState<Plan | null>(null), [items, setItems] = useState<Item[]>([]), [selected, setSelected] = useState(''), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false)
  const canOverride = workspace.role === 'admin'
  const load = async () => { setLoading(true); const [catalogueResult, planResult] = await Promise.all([supabase.from('treatment_catalogue').select('*,treatment_categories(name)').eq('clinic_id', workspace.clinicId).eq('active', true).order('name'), supabase.from('patient_treatment_plans').select('id,additional_adjustment').eq('patient_id', patient.id).eq('clinic_id', workspace.clinicId).eq('status', 'active').maybeSingle()]); if (catalogueResult.error || planResult.error) onNotice(catalogueResult.error?.message || planResult.error?.message || 'Could not load the treatment plan.'); setCatalogue((catalogueResult.data || []) as CatalogueItem[]); const currentPlan = planResult.data as Plan | null; setPlan(currentPlan); if (currentPlan) { const itemResult = await supabase.from('patient_treatment_items').select('*').eq('treatment_plan_id', currentPlan.id).order('created_at'); if (itemResult.error) onNotice(itemResult.error.message); setItems((itemResult.data || []) as Item[]) } else setItems([]); setLoading(false) }
  useEffect(() => { void load() }, [patient.id, workspace.clinicId])
  const add = async () => { const treatment = catalogue.find(item => item.id === selected); if (!treatment) return; setSaving(true); let activePlan = plan; if (!activePlan) { const user = (await supabase.auth.getUser()).data.user; const created = await supabase.from('patient_treatment_plans').insert({ organization_id: workspace.organizationId, clinic_id: workspace.clinicId, patient_id: patient.id, status: 'active', created_by: user?.id }).select('id,additional_adjustment').single(); if (created.error || !created.data) { setSaving(false); onNotice(created.error?.message || 'Could not create a treatment plan.'); return }; activePlan = created.data as Plan; setPlan(activePlan) }
    const price = Number(treatment.standard_price || 0); const next = calc(price, 1, 0); const user = (await supabase.auth.getUser()).data.user; const result = await supabase.from('patient_treatment_items').insert({ organization_id: workspace.organizationId, clinic_id: workspace.clinicId, patient_id: patient.id, treatment_plan_id: activePlan.id, treatment_catalogue_id: treatment.id, treatment_name_snapshot: treatment.name, unit_price_snapshot: price, quantity: 1, discount_percent: 0, discount_amount: 0, final_price: next.final, status: 'Planned', created_by: user?.id }).select().single(); setSaving(false); if (result.error) { onNotice(result.error.message); return }; setItems(current => [...current, result.data as Item]); setSelected(''); onNotice(`${treatment.name} added using the current clinic price.`) }
  const update = async (item: Item, patch: Partial<Item>) => { const price = patch.unit_price_snapshot ?? item.unit_price_snapshot; const quantity = Number(patch.quantity ?? item.quantity); const discount = Number(patch.discount_percent ?? item.discount_percent); const totals = calc(price, quantity, discount); const payload = { ...patch, quantity, discount_percent: discount, discount_amount: totals.discountAmount, final_price: totals.final, custom_price: patch.custom_price ?? item.custom_price }; const { data, error } = await supabase.from('patient_treatment_items').update(payload).eq('id', item.id).eq('clinic_id', workspace.clinicId).select().single(); if (error) { onNotice(error.message); return }; setItems(current => current.map(row => row.id === item.id ? data as Item : row)) }
  const remove = async (item: Item) => { if (!window.confirm(`Remove ${item.treatment_name_snapshot} from this treatment plan?`)) return; const { error } = await supabase.from('patient_treatment_items').delete().eq('id', item.id).eq('clinic_id', workspace.clinicId); if (error) onNotice(error.message); else setItems(current => current.filter(row => row.id !== item.id)) }
  const totals = useMemo(() => items.filter(item => item.status !== 'Cancelled').reduce((result, item) => { const subtotal = item.unit_price_snapshot * item.quantity; result.subtotal += subtotal; result.discount += item.discount_amount; result.final += item.final_price; return result }, { subtotal: 0, discount: 0, final: 0 }), [items])
  const adjustment = Number(plan?.additional_adjustment || 0), estimate = totals.final + adjustment
  return <section className="clinical-section treatment-plan" id="treatment-plan"><div className="clinical-section-head"><div><span className="section-number">04</span><div><h3>Treatment plan</h3><p>Select the clinic catalogue treatment; its configured price is saved as a patient-specific snapshot.</p></div></div></div>
    <div className="plan-add"><select value={selected} onChange={event => setSelected(event.target.value)} disabled={loading}><option value="">Search the treatment catalogue…</option>{catalogue.map(item => <option key={item.id} value={item.id}>{item.name} · {item.treatment_categories?.name || 'Other'} {item.standard_price ? `· ${money(item.standard_price)}` : '· Price not set'}</option>)}</select><button type="button" className="primary" disabled={!selected || saving} onClick={() => void add()}><Plus size={16}/>Add treatment</button></div>
    {!loading && !catalogue.length && <p className="catalogue-empty">No active treatments are available yet. An administrator can configure them under Admin controls → Finance.</p>}
    {items.length > 0 && <div className="plan-table-wrap"><div className="plan-table"><div className="plan-row plan-head"><span>Treatment</span><span>Tooth / region</span><span>Qty</span><span>Unit price</span><span>Discount</span><span>Final</span><span>Status</span><span /></div>{items.map(item => { const original = item.unit_price_snapshot * item.quantity; return <div className="plan-row" key={item.id}><span><b>{item.treatment_name_snapshot}</b>{item.custom_price && <small>Custom price{item.price_adjustment_reason ? ` · ${item.price_adjustment_reason}` : ''}</small>}</span><span><input aria-label="Tooth or region" defaultValue={item.tooth_or_region || ''} placeholder="e.g. 46 / Full arch" onBlur={event => void update(item, { tooth_or_region: event.target.value || null })}/></span><span><input aria-label="Quantity" type="number" min="1" defaultValue={item.quantity} onBlur={event => void update(item, { quantity: Math.max(1, Number(event.target.value || 1)) })}/></span><span><input aria-label="Unit price" type="number" min="0" defaultValue={item.unit_price_snapshot} disabled={!canOverride} onBlur={event => void update(item, { unit_price_snapshot: Number(event.target.value || 0), custom_price: Number(event.target.value || 0) !== item.unit_price_snapshot })}/>{!canOverride && <small>{money(item.unit_price_snapshot)}</small>}</span><span><input aria-label="Discount percent" type="number" min="0" max="100" defaultValue={item.discount_percent} onBlur={event => void update(item, { discount_percent: Number(event.target.value || 0) })}/><small>−{money(item.discount_amount)}</small></span><span><b>{money(item.final_price)}</b><small>of {money(original)}</small></span><span><select aria-label="Treatment status" defaultValue={item.status} onChange={event => void update(item, { status: event.target.value })}>{statuses.map(status => <option key={status}>{status}</option>)}</select></span><span><button type="button" className="icon-btn danger-icon" aria-label={`Remove ${item.treatment_name_snapshot}`} onClick={() => void remove(item)}><Trash2 size={15}/></button></span></div> })}</div></div>}
    <div className="estimate-summary"><div><span>Subtotal</span><b>{money(totals.subtotal)}</b></div><div><span>Treatment discounts</span><b>−{money(totals.discount)}</b></div><label>Additional adjustment<input type="number" value={adjustment} onChange={event => { const value = Number(event.target.value || 0); setPlan(current => current ? { ...current, additional_adjustment: value } : current); if (plan) void supabase.from('patient_treatment_plans').update({ additional_adjustment: value }).eq('id', plan.id).eq('clinic_id', workspace.clinicId) }}/></label><div className="estimate-total"><span>Estimated treatment total</span><b>{money(estimate)}</b><small>Total savings: {money(totals.discount)}</small></div></div>
    <div className="estimate-actions"><button type="button" className="ghost" disabled>Generate estimate <small>Coming soon</small></button><button type="button" className="ghost" disabled>Generate invoice <small>Coming soon</small></button><button type="button" className="primary" onClick={() => onNotice('Treatment plan saved. Its price snapshots are ready for future billing.')}>Save treatment plan</button></div>
  </section>
}
