import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { ChevronDown, Download, Pencil, Plus, Search, Upload } from 'lucide-react'
import { supabase } from './lib/supabase'

export type PricingWorkspace = { organizationId: string; clinicId: string; role: string }
export type CatalogueItem = { id: string; name: string; internal_code: string | null; standard_price: number | null; pricing_unit: string; tax_applicable: boolean; active: boolean; description: string | null; category_id: string; treatment_categories?: { name: string } | null; updated_at: string }
type Category = { id: string; name: string; sort_order: number }
const units = ['Per treatment', 'Per tooth', 'Per surface', 'Per quadrant', 'Per arch', 'Per unit', 'Per implant', 'Per session', 'Per visit', 'Per stage', 'Full case', 'Per image', 'Per site', 'Per appliance', 'Custom']
const rupees = (value: number | null | undefined) => value && value > 0 ? `₹${value.toLocaleString('en-IN')}` : 'Not set'

export function TreatmentPriceList({ workspace, onNotice }: { workspace: PricingWorkspace; onNotice: (message: string) => void }) {
  const [categories, setCategories] = useState<Category[]>([]), [items, setItems] = useState<CatalogueItem[]>([])
  const [query, setQuery] = useState(''), [filter, setFilter] = useState<'all' | 'active' | 'inactive'>('all'), [open, setOpen] = useState<string | null>(null)
  const [editing, setEditing] = useState<CatalogueItem | null>(null), [adding, setAdding] = useState(false), [saving, setSaving] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)
  const canEdit = workspace.role === 'admin'
  const load = async () => {
    const [categoryResult, catalogueResult] = await Promise.all([
      supabase.from('treatment_categories').select('id,name,sort_order').eq('clinic_id', workspace.clinicId).order('sort_order'),
      supabase.from('treatment_catalogue').select('*,treatment_categories(name)').eq('clinic_id', workspace.clinicId).order('name'),
    ])
    if (categoryResult.error || catalogueResult.error) onNotice(categoryResult.error?.message || catalogueResult.error?.message || 'Could not load the treatment catalogue.')
    setCategories((categoryResult.data || []) as Category[]); setItems((catalogueResult.data || []) as CatalogueItem[])
  }
  useEffect(() => { void load() }, [workspace.clinicId])
  const shown = useMemo(() => items.filter(item => (filter === 'all' || (filter === 'active' ? item.active : !item.active)) && `${item.name} ${item.internal_code || ''} ${item.treatment_categories?.name || ''}`.toLowerCase().includes(query.toLowerCase())), [items, query, filter])
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!canEdit) return
    const form = new FormData(event.currentTarget); const id = String(form.get('id') || ''); const payload = {
      name: String(form.get('name') || '').trim(), category_id: String(form.get('category_id') || ''), internal_code: String(form.get('internal_code') || '').trim() || null,
      standard_price: Number(form.get('standard_price') || 0), pricing_unit: String(form.get('pricing_unit') || 'Per treatment'), tax_applicable: form.get('tax_applicable') === 'on', active: form.get('active') === 'on', description: String(form.get('description') || '').trim() || null,
      organization_id: workspace.organizationId, clinic_id: workspace.clinicId,
    }
    if (!payload.name || !payload.category_id) return
    setSaving(true); const result = id ? await supabase.from('treatment_catalogue').update(payload).eq('id', id).eq('clinic_id', workspace.clinicId) : await supabase.from('treatment_catalogue').insert(payload)
    setSaving(false); if (result.error) { onNotice(result.error.message); return }; setEditing(null); setAdding(false); await load(); onNotice(id ? 'Master treatment price updated. Existing patient estimates remain unchanged.' : 'Treatment added to the catalogue.')
  }
  const exportCsv = () => { const rows = [['Treatment', 'Category', 'Code', 'Standard price', 'Pricing unit', 'Tax applicable', 'Status'], ...items.map(item => [item.name, item.treatment_categories?.name || '', item.internal_code || '', String(item.standard_price || 0), item.pricing_unit, item.tax_applicable ? 'Yes' : 'No', item.active ? 'Active' : 'Inactive'])]; const blob = new Blob([rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'sculptos-treatment-price-list.csv'; link.click(); URL.revokeObjectURL(url) }
  const importCsv = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !canEdit) return; const text = await file.text(); const lines = text.split(/\r?\n/).slice(1).filter(Boolean); const categoryByName = new Map(categories.map(category => [category.name.toLowerCase(), category.id])); const rows = lines.map(line => line.split(',').map(value => value.trim().replace(/^"|"$/g, '').replaceAll('""', '"'))).map(([name, category, code, price, unit, tax, status]) => ({ name, category_id: categoryByName.get((category || '').toLowerCase()) || categories.find(item => item.name === 'Other / Custom Treatment')?.id, internal_code: code || null, standard_price: Number(price || 0), pricing_unit: units.includes(unit) ? unit : 'Per treatment', tax_applicable: /yes|true/i.test(tax || ''), active: !/inactive|no|false/i.test(status || ''), organization_id: workspace.organizationId, clinic_id: workspace.clinicId })).filter(row => row.name && row.category_id); if (!rows.length) { onNotice('No valid rows found. Export a template first, then use its category names.'); return }; const { error } = await supabase.from('treatment_catalogue').insert(rows); if (error) onNotice(error.message); else { await load(); onNotice(`${rows.length} treatments imported.`) }; event.target.value = '' }
  const current = editing || (adding ? { id: '', name: '', category_id: categories[0]?.id || '', internal_code: '', standard_price: 0, pricing_unit: 'Per treatment', tax_applicable: false, active: true, description: '' } : null)
  return <section className="price-list-page">
    <div className="price-list-header"><div><span className="eyebrow">FINANCE · MASTER CATALOGUE</span><h1>Treatment &amp; Price List</h1><p>Configure the standard treatment charges used for treatment planning, estimates and billing.</p></div>{canEdit && <div className="price-list-actions"><button className="ghost" onClick={() => fileRef.current?.click()}><Upload size={16}/>Import</button><button className="ghost" onClick={exportCsv}><Download size={16}/>Export</button><button className="primary" onClick={() => setAdding(true)}><Plus size={16}/>Add treatment</button><input ref={fileRef} hidden type="file" accept=".csv,text/csv" onChange={event => void importCsv(event)} /></div>}</div>
    <div className="catalogue-tools"><label className="catalogue-search"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search treatments..." /></label><div className="catalogue-filters">{(['all','active','inactive'] as const).map(value => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div></div>
    {!canEdit && <p className="catalogue-readonly">You can view the clinic price list. Only an administrator can change master pricing.</p>}
    <div className="catalogue-groups">{categories.map(category => { const categoryItems = shown.filter(item => item.category_id === category.id); if (!categoryItems.length && query) return null; const expanded = open === category.id; return <div className="catalogue-group" key={category.id}><button className="catalogue-group-head" onClick={() => setOpen(expanded ? null : category.id)}><span><ChevronDown className={expanded ? 'open' : ''} size={17}/><b>{category.name}</b><em>{categoryItems.length} treatments</em></span><span>{expanded ? 'Hide' : 'Show'}</span></button>{expanded && <div className="catalogue-table"><div className="catalogue-row table-head"><span>Treatment</span><span>Code</span><span>Unit</span><span>Standard price</span><span>Status</span><span /></div>{categoryItems.map(item => <div className="catalogue-row" key={item.id}><span><b>{item.name}</b>{item.description && <small>{item.description}</small>}</span><span>{item.internal_code || '—'}</span><span>{item.pricing_unit}</span><span><b>{rupees(item.standard_price)}</b></span><span><i className={item.active ? 'status active' : 'status'}>{item.active ? 'Active' : 'Inactive'}</i></span><span>{canEdit && <button className="icon-btn" aria-label={`Edit ${item.name}`} onClick={() => setEditing(item)}><Pencil size={15}/></button>}</span></div>)}</div>}</div> })}</div>
    {current && <div className="modal-backdrop"><form className="modal treatment-modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{editing ? 'EDIT MASTER TREATMENT' : 'NEW MASTER TREATMENT'}</span><h2>{editing ? 'Edit treatment' : 'Add treatment'}</h2><p>These changes apply only to treatments added after this save.</p></div></div><input name="id" type="hidden" value={current.id}/><div className="form-grid two"><label>Treatment name<input required name="name" defaultValue={current.name}/></label><label>Category<select required name="category_id" defaultValue={current.category_id}>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Treatment code<input name="internal_code" defaultValue={current.internal_code || ''}/></label><label>Pricing unit<select name="pricing_unit" defaultValue={current.pricing_unit}>{units.map(unit => <option key={unit}>{unit}</option>)}</select></label><label>Standard price<input name="standard_price" type="number" min="0" step="0.01" defaultValue={current.standard_price || 0}/></label><label>Description<input name="description" defaultValue={current.description || ''}/></label></div><div className="treatment-switches"><label><input name="tax_applicable" type="checkbox" defaultChecked={current.tax_applicable}/>Tax applicable</label><label><input name="active" type="checkbox" defaultChecked={current.active}/>Active and selectable for new treatment plans</label></div><div className="modal-actions"><button className="ghost" type="button" onClick={() => { setEditing(null); setAdding(false) }}>Cancel</button><button className="primary" disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</button></div></form></div>}
  </section>
}
