begin;
-- Sourced catalogue entries only: no patient, inventory or financial seed records.
-- Pediatric and emergency entries intentionally have no automatic dose/frequency.
alter table public.dental_medicine_references drop constraint dental_medicine_references_frequency_check;
alter table public.dental_medicine_references add constraint dental_medicine_references_frequency_check check(frequency in ('','OD','BID','TID','QID','PRN','STAT'));
alter table public.clinic_medicines drop constraint clinic_medicines_frequency_check;
alter table public.clinic_medicines add constraint clinic_medicines_frequency_check check(frequency in ('','OD','BID','TID','QID','PRN','STAT'));
insert into public.dental_medicine_references(code,name,strength,form,category,route,adult_reference,instructions,cautions,source_url,source_label,reviewed_on,default_dose,frequency) values
('pantop-d-20-10','Pantop D (pantoprazole + domperidone)','20 mg + 10 mg','Capsule','Gastrointestinal','Oral','','Take before a meal on an empty stomach. Swallow whole; do not crush or chew.','Confirm exact formulation, indication and duration; review QT prolongation and interacting medicines. Not routine with every dental prescription.','https://www.aristopharma.co.in/product/pantop-d-20mg-10mg/','Aristo formulation · NHS pantoprazole/domperidone administration','2026-09-12','',''),
('pantop-d-sr-40-30','Pantop D SR (pantoprazole + domperidone)','40 mg + 30 mg SR','Capsule','Gastrointestinal','Oral','','Take before a meal on an empty stomach. Swallow whole; do not crush or chew.','Confirm exact formulation, indication and duration; review QT prolongation and interacting medicines. Not routine with every dental prescription.','https://www.aristopharma.co.in/product/pantop-d-sr-40mg-30mg-sr/','Aristo formulation · NHS pantoprazole/domperidone administration','2026-09-12','',''),
('pantoprazole-40','Pantoprazole','40 mg','Gastro-resistant tablet','Gastrointestinal','Oral','','Take on an empty stomach, 1 hour before a meal. Swallow whole with water.','Confirm indication and liver function; not an automatic dental adjunct.','https://www.nhs.uk/medicines/pantoprazole/how-and-when-to-take-pantoprazole/','NHS / manufacturer prescribing reference','2026-09-12','40 mg','OD'),
('cetirizine-10','Cetirizine','10 mg','Tablet','Antihistamine','Oral','','Take with or without food. Swallow whole with water; avoid driving if drowsy.','For mild allergy, not a substitute for adrenaline in anaphylaxis. Adjust for renal impairment.','https://www.nhs.uk/medicines/cetirizine/how-and-when-to-take-cetirizine/','NHS / manufacturer prescribing reference','2026-09-12','10 mg','OD'),
('paracetamol-liquid-120','Paracetamol','120 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','With or without food. Shake well; measure the prescribed mL with an oral syringe. Avoid other paracetamol products.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration.','https://www.nhs.uk/medicines/paracetamol-for-children/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('paracetamol-liquid-250','Paracetamol','250 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','With or without food. Shake well; measure the prescribed mL with an oral syringe. Avoid other paracetamol products.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration.','https://www.nhs.uk/medicines/paracetamol-for-children/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('ibuprofen-liquid-100','Ibuprofen','100 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','Give with or after food. Shake well; measure the prescribed mL with an oral syringe. Avoid other NSAIDs.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration. Check dehydration, renal disease and NSAID sensitivity.','https://www.medicinesforchildren.org.uk/medicines/ibuprofen-for-pain-and-inflammation/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('amoxicillin-liquid-125','Amoxicillin','125 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','Give with or without food. Shake well; measure the prescribed mL with an oral syringe. Space doses evenly.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration. Check penicillin allergy and antibiotic indication.','https://www.nhs.uk/medicines/amoxicillin/how-and-when-to-take-amoxicillin/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('amoxicillin-liquid-250','Amoxicillin','250 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','Give with or without food. Shake well; measure the prescribed mL with an oral syringe. Space doses evenly.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration. Check penicillin allergy and antibiotic indication.','https://www.nhs.uk/medicines/amoxicillin/how-and-when-to-take-amoxicillin/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('co-amoxiclav-liquid-400-57','Amoxicillin + clavulanic acid','400 mg + 57 mg/5 mL','Oral suspension','Pediatric liquids','Oral','','Give at the start of a meal. Shake well; measure the prescribed mL with an oral syringe. Follow the pack storage instructions.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration. Check penicillin allergy. Ratios and strengths are not interchangeable.','https://www.medicines.org.uk/emc/product/10902/smpc','NHS / manufacturer prescribing reference','2026-09-12','',''),
('cetirizine-liquid-5','Cetirizine','5 mg/5 mL','Oral solution','Pediatric liquids','Oral','','Give with or without food. Measure the prescribed mL with an oral syringe.','Prescriber must confirm age, weight, concentration, dose in mg and mL, frequency and duration. Review renal function; not treatment for anaphylaxis.','https://www.nhs.uk/medicines/cetirizine/how-and-when-to-take-cetirizine/','NHS / manufacturer prescribing reference','2026-09-12','',''),
('emergency-adrenaline-1','Adrenaline (epinephrine)','1 mg/mL (1:1,000)','Injection','Emergency','IM','','For clinician administration by IM injection for anaphylaxis. Follow the emergency protocol and arrange urgent transfer.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. This IM formulation must not be used as an IV bolus.','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/anaphylaxis/','SDCEP · Anaphylaxis','2026-09-12','',''),
('emergency-aspirin-300','Aspirin','300 mg','Dispersible tablet','Emergency','Oral','','For suspected heart attack: chew or disperse as directed by the clinician. Do not delay emergency transfer.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. Check aspirin allergy and bleeding risk; not for routine pediatric use.','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/cardiac-emergencies/angina-myocardial-infarction/','SDCEP · Cardiac emergencies','2026-09-12','',''),
('emergency-gtn-400','Glyceryl trinitrate (GTN)','400 micrograms/spray','Metered spray','Emergency','Sublingual','','Spray under the tongue while seated, as directed. Do not inhale the spray.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. Check blood pressure and recent PDE-5 inhibitor use.','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/cardiac-emergencies/angina-myocardial-infarction/','SDCEP · Cardiac emergencies','2026-09-12','',''),
('emergency-salbutamol-100','Salbutamol','100 micrograms/puff','Inhaler','Emergency','Inhalation','','Inhale through a spacer, one puff at a time, following the clinician’s emergency instructions.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. ','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/asthma/','SDCEP · Asthma','2026-09-12','',''),
('emergency-glucagon-1','Glucagon','1 mg/vial','Injection kit','Emergency','IM','','For clinician IM administration after reconstitution as directed on the kit. Do not give anything by mouth until safe to swallow.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. Age and weight affect dose.','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/hypoglycaemia/','SDCEP · Hypoglycaemia','2026-09-12','',''),
('emergency-midazolam-5','Midazolam','5 mg/mL','Oromucosal solution','Emergency','Buccal','','For trained administration into the cheek pouch during a prolonged seizure, following the emergency plan. Do not inject this oral product.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. Confirm age-specific dose, formulation and respiratory monitoring.','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/epilepsy/','SDCEP · Epilepsy','2026-09-12','',''),
('emergency-oxygen','Medical oxygen','100%','Medical gas','Emergency','Inhalation','','For clinician administration by an appropriate mask. Set flow and monitor oxygen saturation according to the emergency protocol.','Emergency use by trained clinicians under the clinic protocol; dose, repeat interval and monitoring must be specified. ','https://www.sdcepdentalprescribing.nhs.scot/guidance/medical-emergencies/drugs-for-medical-emergencies/','SDCEP · Emergency medicines','2026-09-12','','');
update public.dental_medicine_references set instructions='Take with or without food. Swallow with water. Avoid other medicines containing paracetamol.',reviewed_on='2026-09-12' where code='paracetamol-500';
update public.dental_medicine_references set instructions='Take with or after food. Swallow whole; do not crush or chew. Avoid other NSAIDs.',reviewed_on='2026-09-12' where code='diclofenac-50';
update public.dental_medicine_references set instructions='Take with or without food. Swallow whole with water and space doses evenly. Follow the prescribed course and review.',reviewed_on='2026-09-12' where code='amoxicillin-500';
update public.dental_medicine_references set instructions='Take with or just after food. Swallow whole. Avoid alcohol during treatment and for 48 hours after the last dose.',reviewed_on='2026-09-12' where code='metronidazole-400';
-- Supplementary administration sources (original dose references remain attached):
-- https://www.nhs.uk/medicines/paracetamol-for-adults/
-- https://www.nhs.uk/medicines/diclofenac/how-and-when-to-take-or-use-diclofenac/
-- https://www.nhs.uk/medicines/amoxicillin/how-and-when-to-take-amoxicillin/
-- https://www.nhs.uk/medicines/metronidazole/how-and-when-to-take-or-use-metronidazole/
-- https://www.nhs.uk/medicines/domperidone/how-and-when-to-take-domperidone/
commit;
